### ISSUE TITLE
Failed to use SDXL lora

### ISSUE THREAD

**Issue by Finenyaco** [gpustack/llama-box#11]
Some errors reported when using SDXL lora
```
/home/sophia/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/gpustack/third_party/bin/llama-box/llama-box --host 0.0.0.0 --embeddings --gpu-layers -1 --parallel 4 --ctx-size 8192 --port 41010 --model /opt/models/huggingface/models--gpustack--stable-diffusion-xl-base-1.0-GGUF/snapshots/f00927e80a399ecb0bcacca868131d5e9d4e77aa/./stable-diffusion-xl-base-1.0-FP16.gguf --no-mmap --no-warmup --images --image-vae-tiling --no-warmup --image-no-vae-model-offload --lora /opt/lora/trend_XL_2.safetensors
/home/runner/work/llama-box/llama-box/llama.cpp/ggml/src/ggml.c:2703: GGML_ASSERT(ggml_can_mul_mat(a, b)) failed
gdb: warning: Couldn't determine a path for the index cache directory.
[New LWP 762336]
[New LWP 762337]
[New LWP 762338]
[New LWP 762339]
[New LWP 762340]
[New LWP 762341]
[New LWP 762342]
[New LWP 762343]
[New LWP 762344]
[New LWP 762345]
[New LWP 762346]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007ff557aea42f in __GI___wait4 (pid=762347, stat_loc=0x7ffc58e08944, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
30	../sysdeps/unix/sysv/linux/wait4.c: No such file or directory.
#0  0x00007ff557aea42f in __GI___wait4 (pid=762347, stat_loc=0x7ffc58e08944, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
30	in ../sysdeps/unix/sysv/linux/wait4.c
#1  0x00000000009cb99a in ggml_abort ()
#2  0x00000000009d2d69 in ggml_mul_mat ()
#3  0x0000000000605759 in LoraModel::build_lora_graph(std::map<std::string, ggml_tensor*, std::less<std::string>, std::allocator<std::pair<std::string const, ggml_tensor*> > >) ()
#4  0x000000000060df04 in std::_Function_handler<ggml_cgraph* (), LoraModel::apply(std::map<std::string, ggml_tensor*, std::less<std::string>, std::allocator<std::pair<std::string const, ggml_tensor*> > >, int)::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
#5  0x00000000005e59bb in GGMLRunner::compute(std::function<ggml_cgraph* ()>, int, bool, ggml_tensor**, ggml_context*) ()
#6  0x000000000060e632 in StableDiffusionGGML::apply_lora(std::string const&, float) ()
#7  0x00000000005d0fd1 in sd_lora_adapters_apply ()
#8  0x00000000004764db in common_sd_init_from_params(stablediffusion_params) ()
#9  0x00000000004e73ae in server_context::load_model(llama_box_params&) ()
#10 0x0000000000437ade in main ()
[Inferior 1 (process 762333) detached]
```

```
/home/sophia/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/gpustack/third_party/bin/llama-box/llama-box --host 0.0.0.0 --embeddings --gpu-layers -1 --parallel 4 --ctx-size 8192 --port 40187 --model /opt/models/huggingface/models--gpustack--stable-diffusion-xl-base-1.0-GGUF/snapshots/f00927e80a399ecb0bcacca868131d5e9d4e77aa/./stable-diffusion-xl-base-1.0-FP16.gguf --no-mmap --no-warmup --images --image-vae-tiling --no-warmup --image-no-vae-model-offload --lora /opt/lora/SDXL_sketch_Lora_v1.0.safetensors
/home/runner/work/llama-box/llama-box/llama.cpp/ggml/src/ggml.c:3025: GGML_ASSERT(ggml_nelements(a) == ggml_nelements(b)) failed
gdb: warning: Couldn't determine a path for the index cache directory.
[New LWP 762607]
[New LWP 762608]
[New LWP 762609]
[New LWP 762610]
[New LWP 762611]
[New LWP 762612]
[New LWP 762613]
[New LWP 762614]
[New LWP 762615]
[New LWP 762616]
[New LWP 762617]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x0000715d098ea42f in __GI___wait4 (pid=762619, stat_loc=0x7ffc8da10914, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
30	../sysdeps/unix/sysv/linux/wait4.c: No such file or directory.
#0  0x0000715d098ea42f in __GI___wait4 (pid=762619, stat_loc=0x7ffc8da10914, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
30	in ../sysdeps/unix/sysv/linux/wait4.c
#1  0x00000000009cb99a in ggml_abort ()
#2  0x00000000009d3ef9 in ggml_reshape ()
#3  0x0000000000605785 in LoraModel::build_lora_graph(std::map<std::string, ggml_tensor*, std::less<std::string>, std::allocator<std::pair<std::string const, ggml_tensor*> > >) ()
#4  0x000000000060df04 in std::_Function_handler<ggml_cgraph* (), LoraModel::apply(std::map<std::string, ggml_tensor*, std::less<std::string>, std::allocator<std::pair<std::string const, ggml_tensor*> > >, int)::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
#5  0x00000000005e59bb in GGMLRunner::compute(std::function<ggml_cgraph* ()>, int, bool, ggml_tensor**, ggml_context*) ()
#6  0x000000000060e632 in StableDiffusionGGML::apply_lora(std::string const&, float) ()
#7  0x00000000005d0fd1 in sd_lora_adapters_apply ()
#8  0x00000000004764db in common_sd_init_from_params(stablediffusion_params) ()
#9  0x00000000004e73ae in server_context::load_model(llama_box_params&) ()
#10 0x0000000000437ade in main ()
[Inferior 1 (process 762604) detached]
```

**Comment by thxCode** [comment]
@Finenyaco , please give it a shot with v0.0.98.
